#authendication credintials
credentials:
  usernames:
    shanto:
      email: shanto@gmail.com
      name: shanto shuvo
      password: $2b$12$LODrCEH38ATCOpdF7OatYOWAQ8euUWZSXNyHw7Evmy90tPrdU/WwO # Placeholder for hashed password of 'abc'
      
      # email: rohmat@gmail.com
      # name: rohmat
      # password: $2b$12$WDjldO3oBD4F6j/M7JSaEeDoyV/xEs1rqEAIg5d/V0XmhPizaNowy # Placeholder for hashed password of 'def'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  #- kalim@growwithdata.net



db:
  host: "localhost"
  user: "root"
  passwd: "shanto"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "sshantorrohmat@gmail.com"
  pass: 'shanto'